debug: true
secret: s3cr3t
http_port: 7777
rpc_port: 1717
api_version: v1
cache_lifetime: 17
service: Application
database:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password: aden
  name: skeleton
