version: '3'
tasks:
    commit:
        cmds:
            - git commit -am "{{.CLI_ARGS}}"
            - git push
    release:
        cmds:
            - git tag -a {{.CLI_ARGS}} -m "release {{.CLI_ARGS}}"
            - git push origin {{.CLI_ARGS}}
    module:
        cmds:
            - bima dump
            - bima module add {{.CLI_ARGS}}
            - bima clean
            - bima dump
    run:
        cmds:
            - bima dump
            - bima run {{.CLI_ARGS}}
    clean:
        cmds:
            - bima clean
            - bima dump
    update:
        cmds:
            - bima update
            - bima dump
    dump:
        cmds:
            - bima dump
    generate:
        cmds:
            - bima dump
            - bima generate
