version: '3'
tasks:
    build:
        cmds:
            - docker compose stop
            - docker compose build --no-cache
            - docker compose up -d --force-recreate
    commit:
        cmds:
            - git commit -am "{{.CLI_ARGS}}"
            - git push
    release:
        cmds:
            - git tag -a {{.CLI_ARGS}} -m "release {{.CLI_ARGS}}"
            - git push origin {{.CLI_ARGS}}
