version: '3'
tasks:
    commit:
        cmds:
            - git commit -am "{{.CLI_ARGS}}"
            - git push
    release:
        cmds:
            - git tag -a {{.CLI_ARGS}} -m "release {{.CLI_ARGS}}"
            - git push origin {{.CLI_ARGS}}
    module:
        cmds:
            - bima module {{.CLI_ARGS}}
    run:
        cmds:
            - bima run {{.CLI_ARGS}}
    clean:
        cmds:
            - bima clean
    update:
        cmds:
            - bima update
    dump:
        cmds:
            - bima dump
    generate:
        cmds:
            - bima generate
